---
swagger: "2.0"
info:
  description: "The Allele Calling  service provides an API for converting raw sequence\
    \ data to GFE and HLA allele calls."
  version: "0.0.2"
  title: "Allele Calling Service"
  contact:
    email: "mhalagan@nmdp.org"
  license:
    name: "GNU GENERAL PUBLIC LICENSE"
    url: "https://www.gnu.org/licenses/lgpl.html"
paths:
  /act:
    get:
      description: "Get HLA and GFE from consensus sequence or GFE notation"
      operationId: "act_get"
      parameters:
      - name: "locus"
        in: "query"
        description: "Valid HLA locus"
        required: true
        type: "string"
      - name: "sequence"
        in: "query"
        description: "Consensus sequence"
        required: false
        type: "string"
      - name: "gfe"
        in: "query"
        description: "GFE Notation"
        required: false
        type: "string"
      - name: "neo4j_url"
        in: "query"
        description: "URL for the neo4j graph"
        required: false
        type: "string"
      - name: "user"
        in: "query"
        description: "Username for the neo4j graph"
        required: false
        type: "string"
      - name: "password"
        in: "query"
        description: "Password for the neo4j graph"
        required: false
        type: "string"
      - name: "gfe_url"
        in: "query"
        description: "URL for the gfe-service"
        required: false
        type: "string"
      - name: "verbose"
        in: "query"
        description: "Flag for running service in verbose"
        required: false
        type: "boolean"
      responses:
        200:
          description: "HLA and GFE from consensus sequence"
          schema:
            $ref: "#/definitions/AlleleCall"
        404:
          description: "Failed to generate GFE from fasta"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /gfe:
    get:
      description: "Get GFE notation associated with an HLA allele"
      operationId: "gfe_get"
      parameters:
      - name: "hla"
        in: "query"
        description: "HLA allele"
        required: true
        type: "string"
      - name: "neo4j_url"
        in: "query"
        description: "URL for the neo4j graph"
        required: false
        type: "string"
      - name: "user"
        in: "query"
        description: "Username for the neo4j graph"
        required: false
        type: "string"
      - name: "password"
        in: "query"
        description: "Password for the neo4j graph"
        required: false
        type: "string"
      - name: "gfe_url"
        in: "query"
        description: "URL for the gfe-service"
        required: false
        type: "string"
      - name: "verbose"
        in: "query"
        description: "Flag for running service in verbose"
        required: false
        type: "boolean"
      responses:
        200:
          description: "GFE notation associated with an HLA allele"
          schema:
            $ref: "#/definitions/GfeCall"
        404:
          description: "Failed to generate GFE from fasta"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /sequence:
    get:
      description: "Get sequence associated with an HLA allele or GFE notation"
      operationId: "sequence_get"
      parameters:
      - name: "allele"
        in: "query"
        description: "HLA allele or GFE notation"
        required: true
        type: "string"
      - name: "neo4j_url"
        in: "query"
        description: "URL for the neo4j graph"
        required: false
        type: "string"
      - name: "user"
        in: "query"
        description: "Username for the neo4j graph"
        required: false
        type: "string"
      - name: "password"
        in: "query"
        description: "Password for the neo4j graph"
        required: false
        type: "string"
      - name: "gfe_url"
        in: "query"
        description: "URL for the gfe-service"
        required: false
        type: "string"
      - name: "verbose"
        in: "query"
        description: "Flag for running service in verbose"
        required: false
        type: "boolean"
      responses:
        200:
          description: "Sequence associated with an HLA allele or GFE notation"
          schema:
            $ref: "#/definitions/SequenceCall"
        404:
          description: "Failed to generate GFE from fasta"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /ars:
    get:
      description: "Get ARS group associated with a GFE notation or HLA allele"
      operationId: "ars_get"
      parameters:
      - name: "allele"
        in: "query"
        description: "HLA allele or GFE Notation"
        required: true
        type: "string"
      - name: "group"
        in: "query"
        description: "ARS Group Type"
        required: true
        type: "string"
      - name: "neo4j_url"
        in: "query"
        description: "URL for the neo4j graph"
        required: false
        type: "string"
      - name: "user"
        in: "query"
        description: "Username for the neo4j graph"
        required: false
        type: "string"
      - name: "password"
        in: "query"
        description: "Password for the neo4j graph"
        required: false
        type: "string"
      - name: "gfe_url"
        in: "query"
        description: "URL for the gfe-service"
        required: false
        type: "string"
      - name: "verbose"
        in: "query"
        description: "Flag for running service in verbose"
        required: false
        type: "boolean"
      responses:
        200:
          description: "ARS group associated with a GFE notation or HLA allele"
          schema:
            $ref: "#/definitions/ArsCall"
        404:
          description: "Failed to generate GFE from fasta"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /seq_search:
    get:
      description: "Sequence data associated from a specific feature, HLA allele, or GFE notation"
      operationId: "seqsrch_get"
      parameters:
      - name: "locus"
        in: "query"
        description: "HLA locus"
        required: true
        type: "string"
      - name: "start"
        in: "query"
        description: "Starting "
        required: false
        type: "integer"
      - name: "end"
        in: "query"
        description: "Sequence of HLA feature"
        required: false
        type: "integer"
      - name: "hla"
        in: "query"
        description: "HLA Allele"
        required: false
        type: "string"
      - name: "rank"
        in: "query"
        description: "HLA feature rank"
        required: false
        type: "string"
      - name: "type"
        in: "query"
        description: "HLA feature type"
        required: false
        type: "string"
      - name: "neo4j_url"
        in: "query"
        description: "URL for the neo4j graph"
        required: false
        type: "string"
      - name: "user"
        in: "query"
        description: "Username for the neo4j graph"
        required: false
        type: "string"
      - name: "password"
        in: "query"
        description: "Password for the neo4j graph"
        required: false
        type: "string"
      - name: "gfe_url"
        in: "query"
        description: "URL for the gfe-service"
        required: false
        type: "string"
      - name: "verbose"
        in: "query"
        description: "Flag for running service in verbose"
        required: false
        type: "boolean"
      responses:
        200:
          description: "ARS group associated with a GFE notation or HLA allele"
          schema:
            $ref: "#/definitions/ArsCall"
        404:
          description: "Failed to generate GFE from fasta"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /feature_search:
    get:
      description: "GFE notation and HLA alleles associated with a specific feature sequence or HLA allele"
      operationId: "feature_get"
      parameters:
      - name: "hla"
        in: "query"
        description: "HLA Allele"
        required: true
        type: "string"
      - name: "feature"
        in: "query"
        description: "HLA feature rank"
        required: true
        type: "array"
          items:
            type: "string"
      - name: "neo4j_url"
        in: "query"
        description: "URL for the neo4j graph"
        required: false
        type: "string"
      - name: "user"
        in: "query"
        description: "Username for the neo4j graph"
        required: false
        type: "string"
      - name: "password"
        in: "query"
        description: "Password for the neo4j graph"
        required: false
        type: "string"
      - name: "gfe_url"
        in: "query"
        description: "URL for the gfe-service"
        required: false
        type: "string"
      - name: "verbose"
        in: "query"
        description: "Flag for running service in verbose"
        required: false
        type: "boolean"
      responses:
        200:
          description: "ARS group associated with a GFE notation or HLA allele"
          schema:
            $ref: "#/definitions/ArsCall"
        404:
          description: "Failed to generate GFE from fasta"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  Error:
    type: "object"
    required:
    - "Message"
    - "version"
    properties:
      Message:
        type: "string"
      accession:
        type: "string"
      file:
        type: "string"
      gfe:
        type: "string"
      log:
        type: "array"
        items:
          type: "string"
      rank:
        type: "integer"
      sequence:
        type: "string"
      term:
        type: "string"
      type:
        type: "string"
      version:
        type: "string"


  GfeCall:
    type: "object"
    properties:
      share_ars:
        type: "array"
        items:
          $ref: "#/definitions/Typing"
      hla:
        type: "string"
      version:
        type: "string"
    example:
      hla: "HLA-A*01:01:01:01"
      gfe:
      - "HLA-Aw1-1-7-20-10-32-7-1-1-1-6-1-5-3-5-1-0"
      share_ars:
        - gfe: "HLA-Aw1-1-7-20-10-32-7-1-1-1-6-1-5-3-5-1-0"
          hla:
          - "HLA-A*01:01:01:02"
          - "HLA-A*01:01:01:01"
      act_version: "0.0.1"
      gfe_version: "0.0.1"
      gfedb_version: "0.0.1"

  Typing:
    type: "object"
    properties:
      hla:
        type: "array"
        items:
          type: "string"
      gfe:
        type: "string"
    example:
      gfe: "HLA-Aw1-1-7-20-10-32-7-1-1-1-6-1-5-3-5-1-0"
      hla:
      - "HLA-A*01:01:01:02"
      - "HLA-A*01:01:01:01"

  AlleleCall:
    type: "object"
    properties:
      typing:
        type: "array"
        items:
          $ref: "#/definitions/ClosestTyping"
      features:
        type: "array"
        items:
            $ref: "#/definitions/Feature"
      gfe:
        type: "string"
      version:
        type: "string"
    example:
      gfe: "HLA-Aw1-1-7-20-10-32-7-1-1-1-6-1-5-3-5-1-1"
      hla:
      - "HLA-A*01:01:01:02"
      - "HLA-A*01:01:01:01"
      act_version: "0.0.1"
      gfe_version: "0.0.1"
      gfedb_version: "0.0.1"

  Feature:
    example:
      accession: 1
      locus: HLA-A
      rank: 1
      sequence: ACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTG
      term: exon
    properties:
      accession:
        type: integer
      rank:
        type: integer
      sequence:
        type: string
      term:
        type: string
    type: object


  ClosestTyping:
    type: "object"
    properties:
      hla:
        type: "string"
      gfe:
        type: "array"
        items:
          $ref: "#/definitions/GfeTyping"
    example:
      allele: "HLA-A*01:01:01:01"

  GfeTyping:
    type: "object"
    properties:
      gfe:
        type: "string"
      features_shared:
        type: "number"
      shares:
        type: "array"
        items:
          $ref: "#/definitions/Feature"
    example:
      allele: "HLA-A*01:01:01:01"


  ArsCall:
    type: "object"
    properties:
      allele:
        type: "string"
      group_type:
        type: "string"
      group:
        type: "string"
      share_ars:
        type: "array"
        items:
          $ref: "#/definitions/Typing"
      version:
        type: "string"
    example:
      allele: "HLA-A*01:01:01:01"
      group_type: "G_GROUP"
      group: "HLA-A*01:01:01G"
      act_version: "0.0.1"
      gfe_version: "0.0.1"
      gfedb_version: "0.0.1"

  SequenceCall:
    type: "object"
    properties:
      sequence:
        type: "array"
        items:
          type: "string"
      version:
        type: "string"
    example:
      sequence:
      - "tccccagacgccgaggatggccgtcatggcgccccgaaccctcctcctgctactctcgggggccctggccctgacccagacctgggcgggtgagtgcggggtcgggagggaaaccgcctctgcggggagaagcaaggggccctcctggcgggggcgcaggaccgggggagccgcgccgggacgagggtcgggcaggtctcagccactgctcgcccccaggctcccactccatgaggtatttcttcacatccgtgtcccggcccggccgcggggagccccgcttcatcgccgtgggctacgtggacgacacgcagttcgtgcggttcgacagcgacgccgcgagccagaggatggagccgcgggcgccgtggatagagcaggaggggccggagtattgggaccaggagacacggaatgtgaaggcccagtcacagactgaccgagtggacctggggaccctgcgcggctactacaaccagagcgaggccggtgagtgaccccggccgggggcgcaggtcaggacccctcatcccccacggacgggccaggtcgcccacagtctccgggtccgagatccaccccgaagccgcgggaccccgagacccttgccccgggagaggcccaggcgcctttacccggtttcattttcagtttaggccaaaaatccccccgggttggtcggggctgggcggggctcgggggactgggctgaccgcggggtcggggccaggttctcacaccatccagataatgtatggctgcgacgtggggtcggacgggcgcttcctccgcgggtaccggcaggacgcctacgacggcaaggattacatcgccctgaacgaggacctgcgctcttggaccgcggcggacatggcggctcagatcaccaagcgcaagtgggaggcggcccatgaggcggagcagttgagagcctacctggatggcacgtgcgtggagtggctccgcagatacctggagaacgggaaggagacgctgcagcgcacgggtaccaggggccacggggcgcctccctgatcgcctgtagatctcccgggctggcctcccacaaggaggggagacaattgggaccaacactagaatatcaccctccctctggtcctgagggagaggaatcctcctgggttccagatcctgtaccagagagtgactctgaggttccgccctgctctctgacacaattaagggataaaatctctgaaggagtgacgggaagacgatccctcgaatactgatgagtggttccctttgacaccggcagcagccttgggcccgtgacttttcctctcaggccttgttctctgcttcacactcaatgtgtgtgggggtctgagtccagcacttctgagtccctcagcctccactcaggtcaggaccagaagtcgctgttcccttctcagggaatagaagattatcccaggtgcctgtgtccaggctggtgtctgggttctgtgctctcttccccatcccgggtgtcctgtccattctcaagatggccacatgcgtgctggtggagtgtcccatgacagatgcaaaatgcctgaattttctgactcttcccgtcagacccccccaagacacatatgacccaccaccccatctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagcgggatggggaggaccagacccaggacacggagctcgtggagaccaggcctgcaggggatggaaccttccagaagtgggcggctgtggtggtgccttctggagaggagcagagatacacctgccatgtgcagcatgagggtctgcccaagcccctcaccctgagatggggtaaggagggagatgggggtgtcatgtctcttagggaaagcaggagcctctctggagacctttagcagggtcagggcccctcaccttcccctcttttcccagagctgtcttcccagcccaccatccccatcgtgggcatcattgctggcctggttctccttggagctgtgatcactggagctgtggtcgctgccgtgatgtggaggaggaagagctcaggtggagaaggggtgaagggtggggtctgagatttcttgtctcactgagggttccaagccccagctagaaatgtgccctgtctcattactgggaagcaccgtccacaatcatgggcctacccagtctgggccctgtgtgccagcacttactcttttgtaaagcacctgttaaaatgaaggacagatttatcaccttgattacggcggtgatgggacctgatcccagcagtcacaagtcacaggggaaggtccctgaggacagacctcaggagggctattggtccaggacccacacctgctttcttcatgtttcctgatcccgccctgggtctgcagtcacacatttctggaaacttctctggggtccaagactaggaggttcctctaggaccttaaggccctggctcctttctggtatctcacaggacattttcttctcacagatagaaaaggagggagttacactcaggctgcaagtaagtatgaaggaggctgatgcctgaggtccttgggatattgtgtttgggagcccatgggggagcccacccacctcacaattcctcctctagccacatcttctgtgggatctgaccaggttctgtttttgttctaccccaggcagtgacagtgcccagggctctgatgtgtccctcacagcttgtaaaggtgagagcttggaggacctaatgtgtgttgggtgttgggcggaacagtggacacagctgtgctatggggtttctttgcattggatgtattgagcatgcgatgggctgtttaaggtgtgacccctcactgtgatggatatgaatttgttcatgaatatttttttctatagtgtgagacagctgccttgtgtgggactgag"
      - "tccccagacgccgaggatggccgtcatggcgccccgaaccctcctcctgctactctcgggggccctggccctgacccagacctgggcgggtgagtgcggggtcgggagggaaaccgcctctgcggggagaagcaaggggccctcctggcgggggcgcaggaccgggggagccgcgccgggacgagggtcgggcaggtctcagccactgctcgcccccaggctcccactccatgaggtatttcttcacatccgtgtcccggcccggccgcggggagccccgcttcatcgccgtgggctacgtggacgacacgcagttcgtgcggttcgacagcgacgccgcgagccagaggatggagccgcgggcgccgtggatagagcaggaggggccggagtattgggaccaggagacacggaatgtgaaggcccagtcacagactgaccgagtggacctggggaccctgcgcggctactacaaccagagcgaggccggtgagtgaccccggccgggggcgcaggtcaggacccctcatcccccacggacgggccaggtcgcccacagtctccgggtccgagatccaccccgaagccgcgggaccccgagacccttgccccgggagaggcccaggcgcctttacccggtttcattttcagtttaggccaaaaatccccccgggttggtcggggctgggcggggctcgggggactgggctgaccgcggggtcggggccaggttctcacaccatccagataatgtatggctgcgacgtggggtcggacgggcgcttcctccgcgggtaccggcaggacgcctacgacggcaaggattacatcgccctgaacgaggacctgcgctcttggaccgcggcggacatggcggctcagatcaccaagcgcaagtgggaggcggcccatgaggcggagcagttgagagcctacctggatggcacgtgcgtggagtggctccgcagatacctggagaacgggaaggagacgctgcagcgcacgggtaccaggggccacggggcgcctccctgatcgcctgtagatctcccgggctggcctcccacaaggaggggagacaattgggaccaacactagaatatcaccctccctctggtcctgagggagaggaatcctcctgggttccagatcctgtaccagagagtgactctgaggttccgccctgctctctgacacaattaagggataaaatctctgaaggagtgacgggaagacgatccctcgaatactgatgagtggttccctttgacaccggcagcagccttgggcccgtgacttttcctctcaggccttgttctctgcttcacactcaatgtgtgtgggggtctgagtccagcacttctgagtccctcagcctccactcaggtcaggaccagaagtcgctgttcccttctcagggaatagaagattatcccaggtgcctgtgtccaggctggtgtctgggttctgtgctctcttccccatcccgggtgtcctgtccattctcaagatggccacatgcgtgctggtggagtgtcccatgacagatgcaaaatgcctgaattttctgactcttcccgtcagacccccccaagacacatatgacccaccaccccatctctgaccatgaggccaccctgaggtgctgggccctgggcttctaccctgcggagatcacactgacctggcagcgggatggggaggaccagacccaggacacggagctcgtggagaccaggcctgcaggggatggaaccttccagaagtgggcggctgtggtggtgccttctggagaggagcagagatacacctgccatgtgcagcatgagggtctgcccaagcccctcaccctgagatggggtaaggagggagatgggggtgtcatgtctcttagggaaagcaggagcctctctggagacctttagcagggtcagggcccctcaccttcccctcttttcccagagctgtcttcccagcccaccatccccatcgtgggcatcattgctggcctggttctccttggagctgtgatcactggagctgtggtcgctgccgtgatgtggaggaggaagagctcaggtggagaaggggtgaagggtggggtctgagatttcttgtctcactgagggttccaagccccagctagaaatgtgccctgtctcattactgggaagcaccgtccacaatcatgggcctacccagtctgggccctgtgtgccagcacttactcttttgtaaagcacctgttaaaatgaaggacagatttatcaccttgattacggcggtgatgggacctgatcccagcagtcacaagtcacaggggaaggtccctgaggacagacctcaggagggctattggtccaggacccacacctgctttcttcatgtttcctgatcccgccctgggtctgcagtcacacatttctggaaacttctctggggtccaagactaggaggttcctctaggaccttaaggccctggctcctttctggtatctcacaggacattttcttctcacagatagaaaaggagggagttacactcaggctgcaagtaagtatgaaggaggctgatgcctgaggtccttgggatattgtgtttgggagcccatgggggagcccacccacctcacaattcctcctctagccacatcttctgtgggatctgaccaggttctgtttttgttctaccccaggcagtgacagtgcccagggctctgatgtgtccctcacagcttgtaaaggtgagagcttggaggacctaatgtgtgttgggtgttgggcggaacagtggacacagctgtgctatggggtttctttgcattggatgtattgagcatgcgatgggctgtttaaggtgtgacccctcactgtgatggatatgaatttgttcatgaatatttttttctatagtgtgagacagctgccttgtgtgggactgag"
      version: "0.0.1"
